import { Deck, Flashcard } from "@/types";

// prettier-ignore
const flashcards: Flashcard[] = [
  // C4 scale
  {note:"F4",buttonIndex:13, action:"pullBellowsButtonPress"},
  {note:"C4",buttonIndex:12, action:"pushBellowsButtonPress"},
  {note:"A4",buttonIndex:14, action:"pullBellowsButtonPress"},
  {note:"E4",buttonIndex:13, action:"pushBellowsButtonPress"},
  {note:"G4",buttonIndex:14, action:"pushBellowsButtonPress"},
  {note:"D4",buttonIndex:12, action:"pullBellowsButtonPress"},
  {note:"B4",buttonIndex:15, action:"pullBellowsButtonPress"},

  // c5 and g and d major key signature
  {note:"C#4",buttonIndex:2, action:"pushBellowsButtonPress"},
  {note:"C5",buttonIndex:15, action:"pushBellowsButtonPress"},
  {note:"D#4",buttonIndex:2, action:"pullBellowsButtonPress"},
  {note:"D5",buttonIndex:16, action:"pullBellowsButtonPress"},
  {note:"F#4",buttonIndex:21, action:"pullBellowsButtonPress"},
  {note:"F5",buttonIndex:17, action:"pullBellowsButtonPress"},
  {note:"E5",buttonIndex:16, action:"pushBellowsButtonPress"},
  {note:"G5",buttonIndex:17, action:"pushBellowsButtonPress"},
  {note:"A5",buttonIndex:18, action:"pullBellowsButtonPress"},
  {note:"B3",buttonIndex:11, action:"pullBellowsButtonPress"},
  {note:"G#4",buttonIndex:4, action:"pushBellowsButtonPress"},
  {note:"C#5",buttonIndex:5, action:"pushBellowsButtonPress"},
  {note:"A3",buttonIndex:20, action:"pullBellowsButtonPress"},
  {note:"F#5",buttonIndex:25, action:"pullBellowsButtonPress"},
  {note:"B5",buttonIndex:19, action:"pullBellowsButtonPress"},
  {note:"G3",buttonIndex:11, action:"pushBellowsButtonPress"},
  {note:"D#5",buttonIndex:5, action:"pullBellowsButtonPress"},
  {note:"G#5",buttonIndex:7, action:"pushBellowsButtonPress"},
  {note:"C6",buttonIndex:18, action:"pushBellowsButtonPress"}, 

  // Fmajor and B flat key signature, alt buttons
  {note:"Bb4",buttonIndex:4, action:"pullBellowsButtonPress"},
  {note:"A4",buttonIndex:3, action:"pushBellowsButtonPress"},
  {note:"Eb4",buttonIndex:2, action:"pullBellowsButtonPress"},
  {note:"D4",buttonIndex:21, action:"pushBellowsButtonPress"},
  {note:"G4",buttonIndex:22, action:"pushBellowsButtonPress"},
  {note:"Bb3",buttonIndex:1, action:"pullBellowsButtonPress"},
  {note:"C5",buttonIndex:23, action:"pullBellowsButtonPress"},
  {note:"Bb5",buttonIndex:7, action:"pullBellowsButtonPress"},

  //C6, Random jitter + by distance to f4
  {note:"A3",buttonIndex:1, action:"pushBellowsButtonPress"}, 
  {note:"Ab4",buttonIndex:4, action:"pushBellowsButtonPress"},
  {note:"C6",buttonIndex:27, action:"pullBellowsButtonPress"},
  {note:"D6",buttonIndex:27, action:"pushBellowsButtonPress"},
  {note:"Gb4",buttonIndex:21, action:"pullBellowsButtonPress"},
  {note:"A4",buttonIndex:22, action:"pullBellowsButtonPress"},
  {note:"Db5",buttonIndex:5, action:"pushBellowsButtonPress"},
  {note:"G3",buttonIndex:10, action:"pullBellowsButtonPress"},
  {note:"A#4",buttonIndex:4, action:"pullBellowsButtonPress"},
  {note:"F#6",buttonIndex:29, action:"pullBellowsButtonPress"},
  {note:"D5",buttonIndex:24, action:"pushBellowsButtonPress"},
  {note:"Db4",buttonIndex:2, action:"pushBellowsButtonPress"},
  
  {note:"G4",buttonIndex:3, action:"pullBellowsButtonPress"},
  
  {note:"A#3",buttonIndex:1, action:"pullBellowsButtonPress"},
  {note:"Eb5",buttonIndex:5, action:"pullBellowsButtonPress"},
  {note:"B3",buttonIndex:20, action:"pushBellowsButtonPress"},
  {note:"E5",buttonIndex:24, action:"pullBellowsButtonPress"},
  {note:"F3",buttonIndex:0, action:"pullBellowsButtonPress"},
  {note:"B4",buttonIndex:23, action:"pushBellowsButtonPress"},
  {note:"E3",buttonIndex:0, action:"pushBellowsButtonPress"},
  {note:"Ab5",buttonIndex:7, action:"pushBellowsButtonPress"},
  {note:"Gb5",buttonIndex:25, action:"pullBellowsButtonPress"},
  {note:"A5",buttonIndex:26, action:"pullBellowsButtonPress"},
  {note:"G5",buttonIndex:25, action:"pushBellowsButtonPress"},
  {note:"B5",buttonIndex:26, action:"pushBellowsButtonPress"},
  {note:"A5",buttonIndex:6, action:"pushBellowsButtonPress"},
  {note:"C3",buttonIndex:10, action:"pushBellowsButtonPress"},
  {note:"C#6",buttonIndex:8, action:"pushBellowsButtonPress"},
  {note:"A#5",buttonIndex:7, action:"pullBellowsButtonPress"},
  {note:"E6",buttonIndex:19, action:"pushBellowsButtonPress"},
  {note:"G5",buttonIndex:6, action:"pullBellowsButtonPress"},
  {note:"G6",buttonIndex:28, action:"pushBellowsButtonPress"},
  {note:"Eb6",buttonIndex:8, action:"pullBellowsButtonPress"},
  {note:"D#6",buttonIndex:8, action:"pullBellowsButtonPress"},
  {note:"Db6",buttonIndex:8, action:"pushBellowsButtonPress"},
  {note:"F6",buttonIndex:9, action:"pullBellowsButtonPress"},
  {note:"Gb6",buttonIndex:29, action:"pullBellowsButtonPress"},
  {note:"E6",buttonIndex:28, action:"pullBellowsButtonPress"},
  {note:"A6",buttonIndex:9, action:"pushBellowsButtonPress"},
  {note:"B6",buttonIndex:29, action:"pushBellowsButtonPress"},
]

export const deck: Deck = {
  id: "angloConcertinaCgWheatstone",
  name: "Anglo Concertina - C/G Wheatstone",
  flashcards,
};

export const cooverDeck: Deck = {
  id: "angloConcertinaCgWheatstone-coover",
  name: "Anglo Concertina - C/G Wheatstone Coover",
  flashcards: [
    { buttonIndex: 10, action: "pushBellowsButtonPress", note: "C3" },
    { buttonIndex: 10, action: "pullBellowsButtonPress", note: "G3" },
    { buttonIndex: 15, action: "pushBellowsButtonPress", note: "C5" },
    { buttonIndex: 15, action: "pullBellowsButtonPress", note: "B4" },
    { buttonIndex: 11, action: "pushBellowsButtonPress", note: "G3" },
    { buttonIndex: 11, action: "pullBellowsButtonPress", note: "B3" },
    { buttonIndex: 16, action: "pushBellowsButtonPress", note: "E5" },
    { buttonIndex: 16, action: "pullBellowsButtonPress", note: "D5" },
    { buttonIndex: 12, action: "pushBellowsButtonPress", note: "C4" },
    { buttonIndex: 12, action: "pullBellowsButtonPress", note: "D4" },
    { buttonIndex: 17, action: "pushBellowsButtonPress", note: "G5" },
    { buttonIndex: 17, action: "pullBellowsButtonPress", note: "F5" },
    { buttonIndex: 13, action: "pushBellowsButtonPress", note: "E4" },
    { buttonIndex: 13, action: "pullBellowsButtonPress", note: "F4" },
    { buttonIndex: 18, action: "pushBellowsButtonPress", note: "C6" },
    { buttonIndex: 18, action: "pullBellowsButtonPress", note: "A5" },
    { buttonIndex: 14, action: "pushBellowsButtonPress", note: "G4" },
    { buttonIndex: 14, action: "pullBellowsButtonPress", note: "A4" },
    { buttonIndex: 19, action: "pushBellowsButtonPress", note: "E6" },
    { buttonIndex: 19, action: "pullBellowsButtonPress", note: "B5" },
    { buttonIndex: 20, action: "pushBellowsButtonPress", note: "B3" },
    { buttonIndex: 20, action: "pullBellowsButtonPress", note: "A3" },
    { buttonIndex: 25, action: "pushBellowsButtonPress", note: "G5" },
    { buttonIndex: 25, action: "pullBellowsButtonPress", note: "F#5" },
    { buttonIndex: 21, action: "pushBellowsButtonPress", note: "D4" },
    { buttonIndex: 21, action: "pullBellowsButtonPress", note: "F#4" },
    { buttonIndex: 26, action: "pushBellowsButtonPress", note: "B5" },
    { buttonIndex: 26, action: "pullBellowsButtonPress", note: "A5" },
    { buttonIndex: 22, action: "pushBellowsButtonPress", note: "G4" },
    { buttonIndex: 22, action: "pullBellowsButtonPress", note: "A4" },
    { buttonIndex: 27, action: "pushBellowsButtonPress", note: "D6" },
    { buttonIndex: 27, action: "pullBellowsButtonPress", note: "C6" },
    { buttonIndex: 23, action: "pushBellowsButtonPress", note: "B4" },
    { buttonIndex: 23, action: "pullBellowsButtonPress", note: "C5" },
    { buttonIndex: 28, action: "pushBellowsButtonPress", note: "G6" },
    { buttonIndex: 28, action: "pullBellowsButtonPress", note: "E6" },
    { buttonIndex: 24, action: "pushBellowsButtonPress", note: "D5" },
    { buttonIndex: 24, action: "pullBellowsButtonPress", note: "E5" },
    { buttonIndex: 29, action: "pushBellowsButtonPress", note: "B6" },
    { buttonIndex: 29, action: "pullBellowsButtonPress", note: "F#6" },
    { buttonIndex: 0, action: "pushBellowsButtonPress", note: "E3" },
    { buttonIndex: 0, action: "pullBellowsButtonPress", note: "F3" },
    { buttonIndex: 5, action: "pushBellowsButtonPress", note: "C#5" },
    { buttonIndex: 5, action: "pullBellowsButtonPress", note: "D#5" },
    { buttonIndex: 1, action: "pushBellowsButtonPress", note: "A3" },
    { buttonIndex: 1, action: "pullBellowsButtonPress", note: "Bb3" },
    { buttonIndex: 6, action: "pushBellowsButtonPress", note: "A5" },
    { buttonIndex: 6, action: "pullBellowsButtonPress", note: "G5" },
    { buttonIndex: 2, action: "pushBellowsButtonPress", note: "C#4" },
    { buttonIndex: 2, action: "pullBellowsButtonPress", note: "D#4" },
    { buttonIndex: 7, action: "pushBellowsButtonPress", note: "G#5" },
    { buttonIndex: 7, action: "pullBellowsButtonPress", note: "Bb5" },
    { buttonIndex: 3, action: "pushBellowsButtonPress", note: "A4" },
    { buttonIndex: 3, action: "pullBellowsButtonPress", note: "G4" },
    { buttonIndex: 8, action: "pushBellowsButtonPress", note: "C#6" },
    { buttonIndex: 8, action: "pullBellowsButtonPress", note: "D#6" },
    { buttonIndex: 4, action: "pushBellowsButtonPress", note: "G#4" },
    { buttonIndex: 4, action: "pullBellowsButtonPress", note: "Bb4" },
    { buttonIndex: 9, action: "pushBellowsButtonPress", note: "A6" },
    { buttonIndex: 9, action: "pullBellowsButtonPress", note: "F6" },
  ],
};
